/**
 * Service Package Seed — 4 userType × 3 tier = 12 paket
 *
 * Çalıştır: npx tsx prisma/seed-service-packages.ts
 */

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

interface PackageSeed {
  name: string;
  slug: string;
  userType: "firma" | "kisi" | "eticaret" | "yurtdisi";
  tier: "temel" | "buyume" | "hakimiyet";
  price: number;
  description: string;
  deliverables: string[];
  auditItemsFixed: string[];
  estimatedScoreBoost: number;
  deliveryDays: number;
}

const PACKAGES: PackageSeed[] = [
  // ═══════════════════════════════════════════════
  // FİRMA
  // ═══════════════════════════════════════════════
  {
    name: "Firma Temel Paket",
    slug: "firma-temel",
    userType: "firma",
    tier: "temel",
    price: 4999,
    description: "Firmanızın AI'larda bulunabilirlik temelini atıyoruz. Schema markup, robots.txt, sitemap ve Google Business optimizasyonu.",
    deliverables: [
      "Organization + LocalBusiness schema ekleme",
      "robots.txt düzenleme (GPTBot, ClaudeBot, Google-Extended izni)",
      "sitemap.xml oluşturma ve Google Search Console'a ekleme",
      "Google Business Profile optimizasyonu",
      "Meta tags (title, description, og:) düzenleme",
    ],
    auditItemsFixed: [
      "schema.organization",
      "schema.localbusiness",
      "tech.robots_txt",
      "tech.sitemap",
      "tech.canonical",
      "entity.gbp",
    ],
    estimatedScoreBoost: 15,
    deliveryDays: 7,
  },
  {
    name: "Firma Büyüme Paketi",
    slug: "firma-buyume",
    userType: "firma",
    tier: "buyume",
    price: 9999,
    description: "Temel paket + içerik otoritesi ve entity sinyalleri. AI'lar firmanızı kaynak olarak görmeye başlayacak.",
    deliverables: [
      "Temel paket tüm deliverable'ları",
      "5 adet SEO-uyumlu blog yazısı (700+ kelime)",
      "FAQ schema + 10 sık sorulan soru sayfası",
      "LinkedIn Company Page optimizasyonu",
      "5 sektör dizinine kayıt (NAP tutarlılığı)",
      "Wikidata item oluşturma",
    ],
    auditItemsFixed: [
      "schema.organization",
      "schema.localbusiness",
      "schema.faq",
      "tech.robots_txt",
      "tech.sitemap",
      "entity.gbp",
      "entity.linkedin",
      "entity.wikidata",
      "entity.directories",
      "entity.nap",
      "content.blog_count",
      "content.faq_format",
    ],
    estimatedScoreBoost: 30,
    deliveryDays: 14,
  },
  {
    name: "Firma Hakimiyet Paketi",
    slug: "firma-hakimiyet",
    userType: "firma",
    tier: "hakimiyet",
    price: 19999,
    description: "Sektörünüzde AI görünürlük liderliği. Kapsamlı içerik otoritesi, dış referanslar ve technical SEO.",
    deliverables: [
      "Büyüme paketi tüm deliverable'ları",
      "15 adet derin içerik (1500+ kelime, how-to, karşılaştırma, orijinal araştırma)",
      "3 sektör medyasına tanıtım yazısı/röportaj",
      "10 kaliteli backlink kampanyası",
      "Review schema + müşteri yorumları entegrasyonu",
      "BreadcrumbList + HowTo schema",
      "Knowledge Panel başvurusu",
      "PageSpeed optimizasyonu (LCP, CLS iyileştirme)",
      "hreflang (çok dilli site için)",
    ],
    auditItemsFixed: [
      "schema.organization",
      "schema.localbusiness",
      "schema.faq",
      "schema.review",
      "schema.howto",
      "schema.breadcrumb",
      "tech.robots_txt",
      "tech.sitemap",
      "tech.pagespeed",
      "tech.canonical",
      "tech.mobile",
      "entity.knowledge_panel",
      "entity.gbp",
      "entity.linkedin",
      "entity.wikidata",
      "entity.directories",
      "entity.nap",
      "entity.brand_ranking",
      "content.blog_count",
      "content.depth",
      "content.variety",
      "content.recency",
      "content.howto",
      "content.comparison",
      "content.original_research",
      "content.faq_format",
      "content.statistics",
      "external.backlinks",
      "external.referring_domains",
      "external.authority",
      "external.media",
    ],
    estimatedScoreBoost: 55,
    deliveryDays: 30,
  },

  // ═══════════════════════════════════════════════
  // KİŞİ (Personal Brand)
  // ═══════════════════════════════════════════════
  {
    name: "Kişisel Temel Paket",
    slug: "kisi-temel",
    userType: "kisi",
    tier: "temel",
    price: 4999,
    description: "Kişisel markanızın AI'larda bulunabilirliği için temel E-E-A-T sinyalleri.",
    deliverables: [
      "LinkedIn profil optimizasyonu (başlık, hakkında, deneyim)",
      "Kişisel web sitesi Person schema",
      "Wikidata item (kişi)",
      "Google Knowledge Panel başvurusu",
      "Öne çıkan 3 sektör dizinine kayıt",
    ],
    auditItemsFixed: [
      "schema.person",
      "entity.linkedin",
      "entity.wikidata",
      "entity.knowledge_panel",
      "entity.directories",
      "eeat.identity",
    ],
    estimatedScoreBoost: 18,
    deliveryDays: 7,
  },
  {
    name: "Kişisel Büyüme Paketi",
    slug: "kisi-buyume",
    userType: "kisi",
    tier: "buyume",
    price: 9999,
    description: "E-E-A-T ve otorite sinyalleri. Sektörünüzde görüş önderi konumuna geliş.",
    deliverables: [
      "Temel paket tüm deliverable'ları",
      "5 adet kişisel blog yazısı (uzmanlık alanı)",
      "3 podcast/röportaj pitch + takip",
      "Akademik/sektörel publication submission (2 adet)",
      "Twitter/X profil optimizasyonu + strateji",
      "GitHub/portfolio (teknik uzmanlar için)",
    ],
    auditItemsFixed: [
      "schema.person",
      "entity.linkedin",
      "entity.wikidata",
      "entity.knowledge_panel",
      "entity.directories",
      "eeat.identity",
      "eeat.expertise",
      "eeat.experience",
      "content.blog_count",
      "content.depth",
      "content.original_research",
      "external.media",
    ],
    estimatedScoreBoost: 35,
    deliveryDays: 14,
  },
  {
    name: "Kişisel Hakimiyet Paketi",
    slug: "kisi-hakimiyet",
    userType: "kisi",
    tier: "hakimiyet",
    price: 19999,
    description: "Sektörünüzde AI'ların ilk öneri olarak gösterdiği kişi konumu. Yüksek otorite.",
    deliverables: [
      "Büyüme paketi tüm deliverable'ları",
      "Medium/Substack blog serisi (10 derinlemesine yazı)",
      "Kitap/e-kitap outline + publishing support",
      "Major medya mention kampanyası (5 hedef)",
      "Konferans speaking pitch (3 etkinlik)",
      "Quora/Reddit uzman yanıt stratejisi",
      "Citation-worthy research/data publishing",
    ],
    auditItemsFixed: [
      "schema.person",
      "entity.linkedin",
      "entity.wikidata",
      "entity.knowledge_panel",
      "entity.directories",
      "eeat.identity",
      "eeat.expertise",
      "eeat.experience",
      "eeat.authoritativeness",
      "eeat.trustworthiness",
      "content.blog_count",
      "content.depth",
      "content.variety",
      "content.recency",
      "content.original_research",
      "content.statistics",
      "external.backlinks",
      "external.referring_domains",
      "external.authority",
      "external.media",
      "external.social",
    ],
    estimatedScoreBoost: 60,
    deliveryDays: 30,
  },

  // ═══════════════════════════════════════════════
  // E-TİCARET
  // ═══════════════════════════════════════════════
  {
    name: "E-Ticaret Temel Paket",
    slug: "eticaret-temel",
    userType: "eticaret",
    tier: "temel",
    price: 4999,
    description: "E-ticaret sitenizin ürünlerinin AI'larda bulunabilirliği için Product schema ve temel optimizasyon.",
    deliverables: [
      "Product schema (tüm ürünlerde)",
      "Organization + LocalBusiness schema",
      "robots.txt + sitemap.xml",
      "Google Merchant Center kaydı",
      "Google Business Profile optimizasyonu",
    ],
    auditItemsFixed: [
      "schema.organization",
      "schema.product",
      "tech.robots_txt",
      "tech.sitemap",
      "entity.gbp",
      "tech.merchant_center",
    ],
    estimatedScoreBoost: 18,
    deliveryDays: 7,
  },
  {
    name: "E-Ticaret Büyüme Paketi",
    slug: "eticaret-buyume",
    userType: "eticaret",
    tier: "buyume",
    price: 9999,
    description: "Ürün karşılaştırma ve review sistemi. AI'lar ürünlerinizi önermeye başlayacak.",
    deliverables: [
      "Temel paket tüm deliverable'ları",
      "Review schema + müşteri yorumları entegrasyonu",
      "10 ürün karşılaştırma blog yazısı",
      "Category pages optimizasyonu (breadcrumb schema)",
      "FAQ schema (her ürün kategorisi için)",
      "Trendyol/Hepsiburada/N11 optimizasyonu",
    ],
    auditItemsFixed: [
      "schema.organization",
      "schema.product",
      "schema.review",
      "schema.breadcrumb",
      "schema.faq",
      "tech.robots_txt",
      "tech.sitemap",
      "entity.gbp",
      "entity.directories",
      "content.blog_count",
      "content.comparison",
      "content.faq_format",
    ],
    estimatedScoreBoost: 35,
    deliveryDays: 14,
  },
  {
    name: "E-Ticaret Hakimiyet Paketi",
    slug: "eticaret-hakimiyet",
    userType: "eticaret",
    tier: "hakimiyet",
    price: 19999,
    description: "E-ticaret sektöründe AI'larda dominant konum. Derin ürün içeriği + dış otorite sinyalleri.",
    deliverables: [
      "Büyüme paketi tüm deliverable'ları",
      "20 derin ürün karşılaştırma içeriği (1500+ kelime)",
      "Influencer/blogger outreach (10 review)",
      "Video content stratejisi (YouTube + 5 video)",
      "Affiliate/partnership referans programı",
      "PageSpeed optimizasyonu (Core Web Vitals)",
      "hreflang (çok dilli site için)",
      "Rich snippets optimizasyonu",
    ],
    auditItemsFixed: [
      "schema.organization",
      "schema.product",
      "schema.review",
      "schema.breadcrumb",
      "schema.faq",
      "schema.howto",
      "tech.robots_txt",
      "tech.sitemap",
      "tech.pagespeed",
      "tech.canonical",
      "tech.mobile",
      "tech.hreflang",
      "entity.gbp",
      "entity.directories",
      "entity.brand_ranking",
      "content.blog_count",
      "content.depth",
      "content.comparison",
      "content.variety",
      "content.recency",
      "content.original_research",
      "content.faq_format",
      "external.backlinks",
      "external.referring_domains",
      "external.authority",
      "external.media",
    ],
    estimatedScoreBoost: 55,
    deliveryDays: 30,
  },

  // ═══════════════════════════════════════════════
  // YURTDIŞI (International)
  // ═══════════════════════════════════════════════
  {
    name: "Yurtdışı Temel Paket",
    slug: "yurtdisi-temel",
    userType: "yurtdisi",
    tier: "temel",
    price: 4999,
    description: "Uluslararası pazarlarda AI bulunabilirliği için hreflang ve çok dilli temel optimizasyon.",
    deliverables: [
      "hreflang tag implementasyonu",
      "Her dil için ayrı sitemap",
      "Organization schema (uluslararası bilgilerle)",
      "İngilizce versiyon için robots.txt + sitemap",
      "International targeting (Google Search Console)",
    ],
    auditItemsFixed: [
      "schema.organization",
      "tech.robots_txt",
      "tech.sitemap",
      "tech.hreflang",
      "tech.canonical",
    ],
    estimatedScoreBoost: 15,
    deliveryDays: 7,
  },
  {
    name: "Yurtdışı Büyüme Paketi",
    slug: "yurtdisi-buyume",
    userType: "yurtdisi",
    tier: "buyume",
    price: 9999,
    description: "Uluslararası entity sinyalleri + çok dilli içerik. İngilizce AI'larda görünürlük.",
    deliverables: [
      "Temel paket tüm deliverable'ları",
      "İngilizce blog yazıları (5 adet, 800+ kelime)",
      "LinkedIn Company Page (İngilizce)",
      "International directories kaydı (Crunchbase, G2, Capterra vb.)",
      "İngilizce FAQ sayfası + schema",
      "Wikipedia/Wikidata uluslararası item",
    ],
    auditItemsFixed: [
      "schema.organization",
      "schema.faq",
      "tech.robots_txt",
      "tech.sitemap",
      "tech.hreflang",
      "tech.canonical",
      "entity.linkedin",
      "entity.wikidata",
      "entity.directories",
      "content.blog_count",
      "content.faq_format",
    ],
    estimatedScoreBoost: 30,
    deliveryDays: 14,
  },
  {
    name: "Yurtdışı Hakimiyet Paketi",
    slug: "yurtdisi-hakimiyet",
    userType: "yurtdisi",
    tier: "hakimiyet",
    price: 19999,
    description: "Uluslararası AI pazarlarda tam hakimiyet. Global otorite, medya ve backlink stratejisi.",
    deliverables: [
      "Büyüme paketi tüm deliverable'ları",
      "İngilizce derin içerik (15 adet, 1500+ kelime)",
      "International PR kampanyası (5 medya hedefi)",
      "Global backlink kampanyası (15 high-DR site)",
      "Product Hunt launch (varsa ürün)",
      "Reddit/HackerNews organik varlık",
      "Industry publications'da guest post (3 adet)",
      "Knowledge Graph entry (global)",
    ],
    auditItemsFixed: [
      "schema.organization",
      "schema.faq",
      "schema.review",
      "schema.howto",
      "schema.breadcrumb",
      "tech.robots_txt",
      "tech.sitemap",
      "tech.pagespeed",
      "tech.hreflang",
      "tech.canonical",
      "tech.mobile",
      "entity.knowledge_panel",
      "entity.linkedin",
      "entity.wikidata",
      "entity.directories",
      "entity.brand_ranking",
      "content.blog_count",
      "content.depth",
      "content.variety",
      "content.recency",
      "content.howto",
      "content.comparison",
      "content.original_research",
      "content.statistics",
      "external.backlinks",
      "external.referring_domains",
      "external.authority",
      "external.media",
      "external.social",
    ],
    estimatedScoreBoost: 55,
    deliveryDays: 30,
  },
];

async function main() {
  console.log("🌱 Seeding service packages...");

  for (const pkg of PACKAGES) {
    await prisma.servicePackage.upsert({
      where: { userType_tier: { userType: pkg.userType, tier: pkg.tier } },
      update: {
        name: pkg.name,
        slug: pkg.slug,
        price: pkg.price,
        description: pkg.description,
        deliverables: pkg.deliverables,
        auditItemsFixed: pkg.auditItemsFixed,
        estimatedScoreBoost: pkg.estimatedScoreBoost,
        deliveryDays: pkg.deliveryDays,
      },
      create: {
        name: pkg.name,
        slug: pkg.slug,
        userType: pkg.userType,
        tier: pkg.tier,
        price: pkg.price,
        description: pkg.description,
        deliverables: pkg.deliverables,
        auditItemsFixed: pkg.auditItemsFixed,
        estimatedScoreBoost: pkg.estimatedScoreBoost,
        deliveryDays: pkg.deliveryDays,
      },
    });
    console.log(`  ✓ ${pkg.userType}/${pkg.tier} — ${pkg.name}`);
  }

  console.log("✅ 12 service packages seeded.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
